### PR TITLE
Add url query parameter option

### PR DESCRIPTION
**Pull request by yolile**

### CODE REVIEW

**Comment by yolile** [comment]
ref #32

**Comment by yolile** [comment]
to test use, for example: 
https://open-contracting.github.io/ocds-show?url=http://www.comprasestatales.gub.uy/ocds/release/llamado-631824

**Comment by kindly** [comment]
I have mixed feelings about this one as it only works for JSON files that have their requests CORS headers set correctly and that is not likely to be the case for lots of publishers.

However, it is a useful feature.

I think I would be a happy if just a slightly better error message explaining that lots of JSON will not work.

**Comment by jpmckinney** [comment]
I'll leave @kindly to review (agree with his comments).

**Comment by robredpath** [comment]
[Update & merge in work to add url query param to ocds-show](https://trello.com/c/YGWhSDNi/8-update-merge-in-work-to-add-url-query-param-to-ocds-show)

**Comment by robredpath** [comment]
@yolile please can you implement David's suggestion of some docs about CORS headers?

**Comment by jpmckinney** [comment]
It turns out this is already implemented but undocumented (uses `load` parameter):

https://open-contracting.github.io/ocds-show/?load=https://www.comprasestatales.gub.uy/ocds/release/llamado-631824

**Pull request closed without merging**
